[package]
description = "Standard library for Neutron with CosmWasm support included"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "neutron-std"
version = "4.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.22", default-features = false }
cosmwasm-std = { workspace = true }
neutron-std-derive = { version = "0.20.1", path = "../neutron-std-derive" }
prost = { workspace = true }
prost-types = { workspace = true }
schemars = { workspace = true }

# for query
serde = {version = "1.0", default-features = false, features = ["derive"]}
serde-cw-value = "0.7.0"
